# Generated by Django 4.2.8 on 2023-12-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BitcoinPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("value", models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name="YourModel",
        ),
    ]
